### PR TITLE
Add UnixTime func to template expansion

### PR DESCRIPTION
**Pull request by nixwiz**
This allows for making timestamps readable and formattable using Golang's time format in a template.

Using the example contained in the test:

`"Check: {{ .Check.Name }} Entity: {{ .Entity.Name }} Executed: {{(UnixTime .Check.Executed).Format \"2 Jan 2006 15:04:05\"}} !"`

When expanded becomes:

`"Check: check-nginx Entity: webserver01 Executed: 10 Dec 2018 20:55:19 !"`

Signed-off-by: Todd Campbell <todd@sensu.io>

### CODE REVIEW

**Review by echlebek — COMMENTED** [review]
Looks good, but do we need documentation?

**Comment by nixwiz** [comment]
> Looks good, but do we need documentation?

Yeah, I didn't see templating in the docs add all.  An opportunity to add it now, I guess?

**Comment by echlebek** [comment]
We probably need it. Would you be able to add some?

**Comment by nixwiz** [comment]
I'll try to write something up.

**Comment by nixwiz** [comment]
@echlebek docs added.

**Review by echlebek — APPROVED** [review]

**Pull request merged**
